#!/usr/bin/env bash
#
# complexity-gate.sh — ratchet function complexity down against a
# committed baseline.
#
#   scripts/complexity-gate.sh check     # CI gate (default)
#   scripts/complexity-gate.sh baseline  # regenerate .complexity-baseline.txt
#
# Thresholds: cyclomatic > 10 (gocyclo), cognitive > 15 (gocognit).
# Non-test Go files under cmd/, internal/, pkg/ are measured; examples/
# and tests are not.
#
# The gate is a ratchet, not a quota:
#
#   1. A function over a threshold that is NOT in the baseline fails
#      the gate — new code must meet the limits.
#   2. A baselined function whose score grew fails the gate — existing
#      offenders may not get worse.
#   3. A baselined function that dropped under the threshold is
#      reported as stale so the baseline can be shrunk; the gate
#      still passes. Run `baseline` to record the improvement.
#
# Baseline format, one entry per line, TAB-separated:
#   <tool>\t<score>\t<package>\t<function>\t<file>
# Line numbers are deliberately omitted so unrelated edits do not
# churn the file.
#
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

MODE="${1:-check}"
BASELINE=".complexity-baseline.txt"
CYCLO_MAX=10
COGNIT_MAX=15
GOCYCLO="github.com/fzipp/gocyclo/cmd/gocyclo@v0.6.0"
GOCOGNIT="github.com/uudashr/gocognit/cmd/gocognit@v1.3.0"

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

find cmd internal pkg -name '*.go' -not -name '*_test.go' | sort > "$tmp/files"

# Both tools print: "<score> <package> <func> <file>:<line>:<col>" and
# exit 1 when anything is over the limit, which xargs reports as 123.
# That is the expected case here, so only other exit codes abort.
run_tool() {
    xargs go run "$1" -over "$2" < "$tmp/files" 2>/dev/null || [ "$?" -eq 123 ]
}

# Normalise to the baseline format and sort for stable diffs.
measure() {
    {
        run_tool "$GOCYCLO" "$CYCLO_MAX" \
            | awk '{ sub(/:[0-9]+:[0-9]+$/, "", $4); printf "cyclo\t%s\t%s\t%s\t%s\n", $1, $2, $3, $4 }'
        run_tool "$GOCOGNIT" "$COGNIT_MAX" \
            | awk '{ sub(/:[0-9]+:[0-9]+$/, "", $4); printf "cognit\t%s\t%s\t%s\t%s\n", $1, $2, $3, $4 }'
    } | sort -t $'\t' -k1,1 -k3,3 -k4,4 -k5,5
}

measure > "$tmp/current"

if [ "$MODE" = "baseline" ]; then
    {
        echo "# Generated by scripts/complexity-gate.sh baseline — do not edit by hand."
        echo "# tool<TAB>score<TAB>package<TAB>function<TAB>file"
        echo "# cyclomatic > $CYCLO_MAX or cognitive > $COGNIT_MAX. Shrink worst-first."
        cat "$tmp/current"
    } > "$BASELINE"
    echo "complexity-gate: wrote $(grep -vc '^#' "$BASELINE") entries to $BASELINE"
    exit 0
fi

if [ ! -f "$BASELINE" ]; then
    echo "complexity-gate: no $BASELINE (run 'scripts/complexity-gate.sh baseline')" >&2
    exit 2
fi

grep -v '^#' "$BASELINE" | sort -t $'\t' -k1,1 -k3,3 -k4,4 -k5,5 > "$tmp/base"

# Key = tool/package/function/file; value = score.
awk -F'\t' '{ print $1"\t"$3"\t"$4"\t"$5"\t"$2 }' "$tmp/base"    > "$tmp/base.kv"
awk -F'\t' '{ print $1"\t"$3"\t"$4"\t"$5"\t"$2 }' "$tmp/current" > "$tmp/cur.kv"

fail=0

# 1. New offenders: in current, not in baseline.
while IFS=$'\t' read -r tool pkg fn file score; do
    if ! grep -qF -- "$tool	$pkg	$fn	$file	" "$tmp/base.kv"; then
        echo "complexity-gate: NEW  $tool=$score  $pkg.$fn  ($file) — over the limit and not baselined" >&2
        fail=1
    fi
done < "$tmp/cur.kv"

# 2. Regressions: baselined, but the score grew.
while IFS=$'\t' read -r tool pkg fn file base_score; do
    cur_score="$(grep -F -- "$tool	$pkg	$fn	$file	" "$tmp/cur.kv" | cut -f5 || true)"
    if [ -n "$cur_score" ] && [ "$cur_score" -gt "$base_score" ]; then
        echo "complexity-gate: WORSE  $tool $base_score -> $cur_score  $pkg.$fn  ($file)" >&2
        fail=1
    fi
done < "$tmp/base.kv"

# 3. Stale baseline entries: improved or removed. Informational.
stale=0
while IFS=$'\t' read -r tool pkg fn file base_score; do
    if ! grep -qF -- "$tool	$pkg	$fn	$file	" "$tmp/cur.kv"; then
        echo "complexity-gate: stale baseline entry $tool=$base_score $pkg.$fn ($file) — run 'make complexity-baseline'"
        stale=$((stale + 1))
    fi
done < "$tmp/base.kv"

total_cur="$(wc -l < "$tmp/current")"
total_base="$(wc -l < "$tmp/base")"
echo "complexity-gate: $total_cur functions over limits (baseline $total_base, stale $stale)"

if [ "$fail" -ne 0 ]; then
    echo "complexity-gate: FAIL — reduce the function's branching or split it; the baseline only shrinks" >&2
    exit 1
fi
echo "complexity-gate: OK"
